In [28]:
import yfinance as yf
from prophet import Prophet
import pandas as pd

# 1. Загрузка данных
# Возьмем, к примеру, индекс S&P 500 (^GSPC) или любую акцию
ticker = "AAPL"
data = yf.download(ticker, start="2020-01-01", end="2024-05-01")

[*********************100%***********************]  1 of 1 completed

In [29]:
data.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400528  72.460791  71.156689  71.409793  135480400
2020-01-03  71.696648  72.455966  71.472469  71.629153  146322800
2020-01-06  72.267921  72.306491  70.568495  70.819193  118387200
2020-01-07  71.928040  72.533080  71.708680  72.277563  108872000
2020-01-08  73.085121  73.386438  71.631567  71.631567  132079200

In [30]:
# 2. Преобразование для Prophet
df_prophet = data[["Close"]].reset_index()
df_prophet.columns = ["ds", "y"]

df_prophet["ds"] = df_prophet["ds"].dt.tz_localize(None)
print("DF ready")
df_prophet.head()

DF ready

          ds          y
0 2020-01-02  72.400528
1 2020-01-03  71.696648
2 2020-01-06  72.267921
3 2020-01-07  71.928040
4 2020-01-08  73.085121

In [31]:
# 3. Инициализация и обучение модели
model = Prophet(daily_seasonality=True)  # для финансовых данных часто полезно
model.fit(df_prophet)

# 4. Создание датафрейма для будущего прогноза (например, на 30 дней вперед)
future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)

# Посмотрим на результат
print(forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].tail())

14:04:46 - cmdstanpy - INFO - Chain [1] start processing
14:04:46 - cmdstanpy - INFO - Chain [1] done processing

             ds        yhat  yhat_lower  yhat_upper
1114 2024-05-26  163.876238  156.659834  172.130987
1115 2024-05-27  162.813295  154.964743  170.623842
1116 2024-05-28  162.635132  155.240338  170.508230
1117 2024-05-29  162.635131  155.260456  170.225338
1118 2024-05-30  162.469821  154.613216  170.161965